---

- name: Install `cascadia-code` font
  include_tasks: cascadia-code/main.yml

- include_tasks: comic-code.yml

- name: Install `fantasque-sans` font
  include_tasks: fantasque-sans/main.yml

- name: Install `fira-code` font
  include_tasks: fira-code/main.yml

- name: Install `iosevka` font
  include_tasks: iosevka/main.yml

- name: Install `jetbrains-mono` font
  include_tasks: jetbrains-mono/main.yml

- name: Update font cache
  shell: fc-cache -f -v
