---
- block:
  - name: Add `regolith-linux` repository from PPA with the current codename
    become: yes
    apt_repository:
      repo: ppa:regolith-linux/release
  rescue:
  - name: Add `regolith-linux` repository from PPA with the `impish` codename
    become: yes
    apt_repository:
      repo: ppa:regolith-linux/release
      codename: impish
