---
- include_tasks: i3.debian.yml
  when: ansible_os_family == "Debian"



- name: Install `i3-gaps` package
  become: yes
  package: 
    name: i3-gaps
    state: latest


- name: Ensures `~/.config/i3` folder exists
  file:
    path: "~/.config/i3"
    state: directory

- name: Deploying the `i3` configuration file
  template:
    src: i3config.j2
    dest: "~/.config/i3/config"

- name: Copy the `i3-get-windows-criteria` script
  copy:
    src: get-window-criteria.sh
    dest: "~/.config/i3/"
    mode: '0754'