---
- name: Install `ckb-next` aur package
  kewlfft.aur.aur:
    use: yay
    name: ckb-next
    state: present


- name: Ensures `~/.config/ckb-next` folder exists
  file:
    path: "~/.config/ckb-next"
    state: directory

- name: Copy the `ckb-next.conf` configuration file
  copy:
    src: ckb-next.conf
    dest: "~/.config/ckb-next/"
    mode: '0664'

- name: Ensure `ckb-next-daemon` is enabled
  become: yes
  service:
    name: ckb-next-daemon
    enabled: yes
    state: started