---
- include_tasks: ckb-next.archlinux.yml
  when: ansible_os_family == "Archlinux"

- include_tasks: ckb-next.debian.yml
  when: ansible_os_family == "Debian"



- name: Ensures `~/.config/ckb-next` folder exists
  file:
    path: "~/.config/ckb-next"
    state: directory

- name: Copy the `ckb-next.conf` configuration file
  copy:
    src: ckb-next.conf
    dest: "~/.config/ckb-next/"
    mode: '0664'

- name: Ensure `ckb-next-daemon` is enabled
  become: yes
  service:
    name: ckb-next-daemon
    enabled: yes
    state: started