---
- name: Install `sddm`
  become: True
  package:
    name: sddm
    state: present

- name: Ensure `sddm` is enabled at boot
  become: True
  service:
    name: sddm
    enabled: yes

- name: Create a symbolic link to `sddm`
  become: True
  file:
    src: /usr/lib/systemd/system/sddm.service
    dest: /etc/systemd/system/display-manager.service
    mode: '777'
    state: link