---
- name: Configure `bash`
  include_role:
    name: shell/bash
    apply: 
      tags: [bash]
  tags: [shell]

- name: Install and configure `zsh`
  include_role:
    name: shell/zsh
    apply: 
      tags: [zsh]
  tags: [shell]

- name: Configure aliases
  include_role:
    name: shell/alias
    apply: 
      tags: [alias]
  tags: [shell]