---
- name: Install `polybar` package
  become: yes
  package: 
    name: polybar
    state: latest


- name: Download `polybar-nord` repository
  git:
    repo: https://github.com/Artmorse/polybar-nord.git
    dest: ~/.config/polybar

- name: Change `launch.sh` file permissions
  file:
    path: ~/.config/polybar/launch.sh
    mode: '0754'

- name: Get scripts files
  find:
    paths: ~/.config/polybar/scripts
  register: polybar_scripts

- name: Change scripts files permissions
  file:
    path: "{{ item }}"
    mode: '0754'
  with_items: "{{ polybar_scripts.files | map(attribute='path') }}"
