---
- hosts: pve

  pre_tasks:
  - name: "Limiting the playbooks execution to Debian distributions."
    fail:
      msg: "{{ ansible_distribution }} is not supported by these playbooks!"
    when: ansible_os_family != "Debian"

  tasks:

    # * essential
    - name: update the system and install the essential packages
      include_role:
        name: essential


    # * system customization
    - name: install some fonts
      include_role: 
        name: fonts

    - name: install colorscheme
      include_role:
        name: colorscheme

    - name: install some themes
      include_role:
        name: themes

    - name: install some icons
      include_role:
        name: icons


    # * peripherals customization
    - name: configure peripherals
      include_role:
        name: peripherals

    - name: configure screenlayout
      include_role:
        name: screenlayout


    # * workspace
    - name: configure ssh workspaces
      include_role:
        name: ssh

    - name: configure git workspaces
      include_role:
        name: git


    # * containerization
    - name: install docker
      include_role:
        name: containerization
      tags: [docker]


    # * terminals
    - name: configure shells
      include_role:
        name: shell

    - name: install and configure terminals
      include_role:
        name: terminal


    # * interface customization
    - name: install notifier
      include_role:
        name: notifications

    - name: configure wallpapers
      include_role:
        name: wallpapers

    - name: install and configure menu application
      include_role:
        name: menu

    - name: install and configure bar
      include_role:
        name: bars

    - name: install and configure window manager
      include_role:
        name: wm


    # * applications
    - name: install screenshot software
      include_role:
        name: screenshot

    - name: install CLI applications
      include_role:
        name: cli
  
    - name: install GUI applications
      include_role: 
        name: gui
      tags: [gui]


    # * reboot
    - name: reboot the machine
      import_tasks: tasks/reboot.yml
      tags: [reboot]
  

    # * containers
    - name: run some containers
      include_role: 
        name: containerization
      tags: [containers]
