---
- hosts: "{{ variable_host | default('localhost') }}"

  pre_tasks:
  - name: "Limiting the playbooks execution to Archlinux distributions."
    fail:
      msg: "{{ ansible_distribution }} is not supported by these playbooks!"
    when: ansible_os_family != "Archlinux"

  tasks:

    # * essential
    - name: update the system and install the essential packages
      include_role:
        name: essential
        apply: 
          tags: [essential]
      tags: [essential]


    # * system customization
    - name: install some fonts
      include_role: 
        name: fonts
        apply: 
          tags: [fonts]
      tags: [fonts]

    - name: install colorscheme
      include_role:
        name: colorscheme
        apply: 
          tags: [colorscheme]
      tags: [colorscheme]

    - name: install some themes
      include_role:
        name: themes
        apply: 
          tags: [themes]
      tags: [themes]

    - name: install some icons
      include_role:
        name: icons
        apply: 
          tags: [icons]
      tags: [icons]

    - name: install file manager
      include_role:
        name: file-manager
      tags: [fileManager]


    # * peripherals configuration
    - name: configure audio
      include_role:
        name: audio
        apply: 
          tags: [audio]
      tags: [audio]

    - name: configure brightness
      include_role:
        name: brightness
        apply: 
          tags: [brightness]
      tags: [brightness]

    - name: configure bluetooth
      include_role:
        name: bluetooth
        apply: 
          tags: [bluetooth]
      tags: [bluetooth]

    - name: configure peripherals
      include_role:
        name: peripherals
      tags: [peripherals]

    - name: configure screenlayout
      include_role:
        name: screenlayout
      tags: [screenlayout]


    # * workspace
    - name: configure ssh workspaces
      include_role:
        name: ssh
        apply: 
          tags: [ssh]
      tags: [ssh]

    - name: configure git workspaces
      include_role:
        name: git
        apply: 
          tags: [git]
      tags: [git]


    # * containerization
    - name: install docker
      include_role:
        name: containerization
        tasks_from: docker
      tags: [docker]


    # * terminals
    - name: configure shells
      include_role:
        name: shell
      tags: [shell]

    - name: install and configure terminals
      include_role:
        name: terminal
      tags: [terminal]


    # * interface customization
    - name: install notifier
      include_role:
        name: notifications
      tags: [notifications]

    - name: install lockscreen
      include_role:
        name: lockscreen
      tags: [lockscreen]

    - name: configure wallpapers
      include_role:
        name: wallpapers
      tags: [wallpapers]

    - name: install and configure menu application
      include_role:
        name: menu
      tags: [menu]

    - name: install and configure bar
      include_role:
        name: bars
      tags: [bars]

    - name: install and configure window manager
      include_role:
        name: wm
      tags: [wm]


    # * applications
    - name: install screenshot software
      include_role:
        name: screenshot
      tags: [screenshot]

    - name: install CLI applications
      include_role:
        name: cli
      tags: [cli]

    - name: install GUI applications
      include_role:
        name: gui
      tags: [gui]


    # * reboot
    - name: reboot the machine
      import_tasks: tasks/reboot.yml
      tags: [reboot]

    # * containers
    - name: run some containers
      include_role: 
        name: containerization
        tasks_from: containers
      tags: [containers]
