---
- name: Upload wallpapers
  include_role:
    name: wallpapers/wallpaper
    apply: 
      tags: [wallpaper]


- name: Install and configure `feh` software
  include_role:
    name: wallpapers/feh
    apply: 
      tags: [wallpaper]
