---
- name: "Adding wheel group to the sudoers."
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: ^%wheel ALL=
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s

#
# Package Managers
#
- name: Update and upgrade pacman packages
  become: yes
  pacman:
    update_cache: yes
    upgrade: 'yes'
  when: ansible_pkg_mgr == 'pacman'

- name: Update and upgrade aptitude packages
  become: yes
  apt:
    update_cache: yes
    upgrade: 'yes'
  when: ansible_pkg_mgr == 'apt'


- name: Install essential packages
  become: yes
  package: 
    name: 
      - git
      # http clients
      - wget
      - curl
      # compress/decompress tools
      - unzip
      - unrar
      # gpg
      - gnupg
      - gnupg2
      # network manager
      - network-manager-gnome
      # misc
      - software-properties-common
      - apt-transport-https
      - ca-certificates


- name: Install `yay` package manager (AUR) and dependencies
  become: yes
  package: 
    name: 
      - yay
      # dependencies
      - gcc
      - patch
      - make
      - pkgconf
      - autoconf
      - automake
    state: latest
  when: ansible_os_family == "Archlinux"


#
# Folders
#

- name: Ensures folders exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "~/.config"
    - "~/.local/share"

#
# Timezone
#

- name: Set timezone
  shell: timedatectl set-timezone {{ timezone }}

- name: Restart `timesyncd` service
  become: yes
  service:
    name: systemd-timesyncd
    state: restarted

#
# Locale
#
- name: Generate the locale
  locale_gen:
    name: "{{ locale }}"
    state: present