---
- name: "Adding wheel group to the sudoers."
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: ^%wheel ALL=
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s
  become: True

#
# Package Managers
#
- name: Update and upgrade pacman packages
  become: yes
  pacman:
    update_cache: yes
    upgrade: 'yes'


- name: Install essential packages
  become: yes
  package: 
    name: 
      - git
      # http clients
      - wget
      - curl
      # compress/decompress tools
      - unzip
      - unrar


- name: Install `yay` package manager (AUR) and dependencies
  become: yes
  package: 
    name: 
      - yay
      # dependencies
      - gcc
      - patch
      - make
      - pkgconf
      - autoconf
      - automake
    state: latest


- name: Install pip
  include_role:
    name: geerlingguy.pip
  vars:
    - ansible_become: yes
    - pip_package: "python-pip"


#
# Folders
#

- name: Ensures folders exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "~/.config"
    - "~/.local/share"

#
# Timezone
#

- name: Set timezone
  shell: timedatectl set-timezone {{ timezone }}

- name: Restart `timesyncd` service
  become: yes
  systemd:
    name: systemd-timesyncd.service
    state: restarted

#
# Locale
#
- name: Generate the locale
  locale_gen:
    name: "{{ locale }}"
    state: present