---
- name: Get latest release informations from Github
  uri:
    url: https://api.github.com/repos/{{ outer_item }}/releases/latest
  register: latest_release

- name: Set *version* variable
  set_fact:
    version: "{{ latest_release['json']['tag_name'] }}"

- name: Get latest version of `{{ outer_item }}` repository
  debug:
    msg: "{{ version }}"
