---
# - name: Install `i3lock-color`
#   include_role:
#     name: lockscreen/i3lock-color
#     apply: 
#       tags: [lockscreen]

# - name: Install `betterlockscreen`
#   include_role:
#     name: lockscreen/betterlockscreen
#     apply: 
#       tags: [lockscreen]

- name: Install `xautolock`
  package:
    name: xautolock
    state: latest

- name: Install `slock`
  include_role:
    name: lockscreen/slock
    apply: 
      tags: [lockscreen]