---
- name: Install `xautolock`
  become: yes
  package:
    name: xautolock
    state: latest
  tags: [lockscreen, xautolock]

- name: Install `slock`
  include_role:
    name: lockscreen/roles/slock
    apply: 
      tags: [lockscreen, slock]
  tags: [lockscreen]