---

- name: Install `xautolock`
  package:
    name: xautolock
    state: latest
  tags: [lockscreen, xautolock]

- name: Install `slock`
  package:
    name: slock
    state: latest
  tags: [lockscreen, slock]