---
- name: Install `blueman`
  become: yes
  package:
    name:
      - blueman
    state: present

- name: Enabling automatic sound switch to connected bluetooth devices
  become: yes
  lineinfile:
    path: /etc/pulse/default.pa
    state: present
    line: "load-module module-switch-on-connect"
