---
#
# communication
#

- name: Install `discord` software
  include_role:
    name: gui/roles/discord
    apply: 
      tags: [communication, discord]
  tags: [gui]
  when: discord.enabled | default(False)


- name: Install `mailspring` software
  include_role:
    name: gui/roles/mailspring
    apply: 
      tags: [communication, mailspring]
  tags: [gui]
  when: mailspring.enabled | default(False)


- name: Install `slack` software
  kewlfft.aur.aur:
    use: yay
    name: slack-desktop
    state: present
  tags: [communication, slack]
  when: slack.enabled | default(False)


- name: Install `teamviewer` software
  kewlfft.aur.aur:
    use: yay
    name: teamviewer
    state: present
  tags: [communication, teamviewer]
  when: teamviewer.enabled | default(False)


- name: Install `zoom` software
  kewlfft.aur.aur:
    use: yay
    name: zoom
    state: present
  tags: [communication, zoom]
  when: zoom.enabled | default(False)



#
# dev
#

- name: Install `VSCode` and `VSCodium` softwares
  include_role:
    name: gui/roles/code
    apply: 
      tags: [dev, code]
  tags: [gui]
  when: code.enabled | default(False)


- name: Install `dbeaver` software
  become: yes
  package:
    name: dbeaver
    state: latest
  tags: [dev, dbeaver]
  when: dbeaver.enabled | default(False)


- name: Install `gitfiend` software
  kewlfft.aur.aur:
    use: yay
    name: gitfiend
    state: present
  tags: [dev, gitfiend]
  when: gitfiend.enabled | default(False)


- name: Install `jetbrains-toolbox` software
  kewlfft.aur.aur:
    use: yay
    name: jetbrains-toolbox
    state: present
  tags: [dev, jetbrainsToolbox]
  when: jetbrainsToolbox.enabled | default(False)


- name: Install `lens` software
  kewlfft.aur.aur:
    use: yay
    name: lens-bin
    state: present
  tags: [dev, lens]
  when: lens.enabled | default(False)


- name: Install `postman` software
  kewlfft.aur.aur:
    use: yay
    name: postman-bin
    state: present
  tags: [dev, postman]
  when: postman.enabled | default(False)



#
# media
#

- name: Install `evince` software
  become: yes
  package:
    name: evince
    state: latest
  tags: [media, evince]
  when: evince.enabled | default(False)


- name: Install `obs-studio` software
  become: yes
  package: 
    name: obs-studio
    state: latest
  tags: [media, obs-studio]
  when: obsStudio.enabled | default(False)


- name: Install `photoflare` software
  become: yes
  package: 
    name: photoflare
    state: latest
  tags: [media, photoflare]
  when: photoflare.enabled | default(False)


- name: Install `ristretto` software
  become: yes
  package:
    name: ristretto
    state: latest
  tags: [media, ristretto]
  when: ristretto.enabled | default(False)


- name: Install `vlc` software
  become: yes
  package: 
    name: vlc
    state: latest
  tags: [media, vlc]
  when: vlc.enabled | default(False)



#
# misc
#

- name: Install `balena-etcher` software
  kewlfft.aur.aur:
    use: yay
    name: balena-etcher
    state: present
  tags: [misc, balenaEtcher]
  when: balenaEtcher.enabled | default(False)
  ignore_errors: yes


- name: Install `bitwarden` software
  become: yes
  package:
    name: bitwarden
    state: latest
  tags: [misc, bitwarden]
  when: bitwarden.enabled | default(False)


- name: Install `cura` software
  include_role:
    name: gui/roles/cura
    apply: 
      tags: [misc, cura]
  tags: [gui]
  when: cura.enabled | default(False)


- name: Install `deluge` software
  become: yes
  package:
    name: deluge-gtk
    state: latest
  tags: [misc, deluge]
  when: deluge.enabled | default(False)


- name: Install `filezilla` software
  become: yes
  package: 
    name: filezilla
    state: latest
  tags: [misc, filezilla]
  when: filezilla.enabled | default(False)


- name: Install `qalculate` software
  become: yes
  package: 
    name: qalculate-gtk
    state: latest
  tags: [misc, qalculate]
  when: qalculate.enabled | default(False)


- name: Install `rpi-imager` software
  kewlfft.aur.aur:
    use: yay
    name: rpi-imager
    state: present
  tags: [misc, rpiImager]
  when: rpiImager.enabled | default(False)



#
# music
#


- name: Install `easyeffects` software
  become: yes
  package: 
    name: easyeffects
    state: latest
  tags: [music, easyeffects]
  when: easyeffects.enabled | default(False)


- name: Install `spotify` software
  include_role:
    name: gui/roles/spotify
    apply: 
      tags: [music, spotify]
  tags: [gui]
  when: spotify.enabled | default(False)



#
# webbrowsers
#

- name: Install `chromium` software
  become: yes
  package: 
    name: chromium
    state: latest
  tags: [webbrowsers, chromium]
  when: chromium.enabled | default(False)

- name: Install `firefox` software
  become: yes
  package: 
    name: firefox
    state: latest
  tags: [webbrowsers, firefox]
  when: firefox.enabled | default(False)
