---
#
# communication
#

- include_role:
    name: gui/roles/discord
    apply: 
      tags: [communication, discord]
  tags: [gui]
  when: discord.enabled | default(False)


- include_role:
    name: gui/roles/mailspring
    apply: 
      tags: [communication, mailspring]
  tags: [gui]
  when: mailspring.enabled | default(False)


- include_tasks: slack/main.yml
  tags: [gui, communication, slack]
  when: slack.enabled | default(False)


- include_tasks: teamviewer/main.yml
  tags: [gui, communication, teamviewer]
  when: teamviewer.enabled | default(False)


- include_tasks: zoom/main.yml
  tags: [gui, communication, zoom]
  when: zoom.enabled | default(False)


#
# dev
#

- include_role:
    name: gui/roles/code
    apply: 
      tags: [dev, code]
  tags: [gui]
  when: code.enabled | default(False)


- include_tasks: dbeaver/main.yml
  tags: [gui, dev, dbeaver]
  when: dbeaver.enabled | default(False)


- include_tasks: gitfiend/main.yml
  tags: [gui, dev, gitfiend]
  when: gitfiend.enabled | default(False)


- include_tasks: jetbrains-toolbox/main.yml
  tags: [gui, dev, jetbrainsToolbox]
  when: jetbrainsToolbox.enabled | default(False)


- include_tasks: lens/main.yml
  tags: [gui, dev, lens]
  when: lens.enabled | default(False)


- include_tasks: postman/main.yml
  tags: [gui, dev, postman]
  when: postman.enabled | default(False)


#
# media
#

- name: Install `evince` software
  become: yes
  package:
    name: evince
    state: latest
  tags: [media, evince]
  when: evince.enabled | default(False)


- name: Install `gthumb` software
  become: yes
  package: 
    name: gthumb
    state: latest
  tags: [media, gthumb]
  when: gthumb.enabled | default(False)


- name: Install `obs-studio` software
  become: yes
  package: 
    name: obs-studio
    state: latest
  tags: [media, obs-studio]
  when: obsStudio.enabled | default(False)


- name: Install `photoflare` software
  become: yes
  package: 
    name: photoflare
    state: latest
  tags: [media, photoflare]
  when: photoflare.enabled | default(False)


- name: Install `ristretto` software
  become: yes
  package:
    name: ristretto
    state: latest
  tags: [media, ristretto]
  when: ristretto.enabled | default(False)


- name: Install `vlc` software
  become: yes
  package: 
    name: vlc
    state: latest
  tags: [media, vlc]
  when: vlc.enabled | default(False)



#
# misc
#

- include_tasks: balena-etcher/main.yml
  tags: [misc, balenaEtcher]
  when: balenaEtcher.enabled | default(False)


- include_tasks: bitwarden/main.yml
  tags: [misc, bitwarden]
  when: bitwarden.enabled | default(False)


- include_role:
    name: gui/roles/cura
    apply: 
      tags: [misc, cura]
  tags: [gui]
  when: cura.enabled | default(False)


- include_tasks: deluge/main.yml
  tags: [misc, deluge]
  when: deluge.enabled | default(False)


- name: Install `filezilla` software
  become: yes
  package: 
    name: filezilla
    state: latest
  tags: [misc, filezilla]
  when: filezilla.enabled | default(False)


- name: Install `qalculate` software
  become: yes
  package: 
    name: qalculate-gtk
    state: latest
  tags: [misc, qalculate]
  when: qalculate.enabled | default(False)


- include_tasks: rpi-imager/main.yml
  tags: [misc, rpiImager]
  when: rpiImager.enabled | default(False)


#
# music
#


- include_tasks: easyeffects/main.yml
  tags: [music, easyeffects]
  when: easyeffects.enabled | default(False)


- include_role:
    name: gui/roles/spotify
    apply: 
      tags: [music, spotify]
  tags: [gui]
  when: spotify.enabled | default(False)



#
# webbrowsers
#

- include_tasks: chromium/main.yml
  tags: [webbrowsers, chromium]
  when: chromium.enabled | default(False)


- name: Install `firefox` software
  become: yes
  package: 
    name: firefox
    state: latest
  tags: [webbrowsers, firefox]
  when: firefox.enabled | default(False)
