---
- name: Install `pip` dependencies
  pip: 
    name: bcrypt

- name: Ensures `~/.ssh` folder exists
  file:
    path: ~/.ssh
    state: directory

- name: Generate `pro` ssh keypair
  community.crypto.openssh_keypair:
    path: "~/.ssh/id_{{ user.pro.ssh_keys.type }}_{{ user.pro.ssh_keys.name }}"
    type: "{{ user.pro.ssh_keys.type }}"
    passphrase: "{{ user.pro.ssh_keys.passphrase }}"
  when: "{{ user.pro.ssh_keys.create_it | default(False) }}"

- name: Generate `perso` ssh keypair
  community.crypto.openssh_keypair:
    path: "~/.ssh/id_{{ user.perso.ssh_keys.type }}_{{ user.perso.ssh_keys.name }}"
    type: "{{ user.perso.ssh_keys.type }}"
    passphrase: "{{ user.perso.ssh_keys.passphrase }}"
  when: "{{ user.perso.ssh_keys.create_it | default(False) }}"



- include_tasks: ssh.archlinux.yml
  when: ansible_os_family == "Archlinux"

- include_tasks: ssh.debian.yml
  when: ansible_os_family == "Debian"
