---
- name: Install `discord` software
  become: yes
  snap:
    name: discord


- name: Add `betterdiscordctl` repository from PPA with the current codename
  become: yes
  apt_repository:
    repo: ppa:chronobserver/betterdiscordctl
    state: present

- name: Install `betterdiscordctl`
  become: yes
  package:
    name: betterdiscordctl
    state: present
