---
- name: Install Adapta Nord themes
  include_tasks: adapta-nord/main.yml

- name: Install Nordic themes
  include_tasks: nordic.yml
  loop: 
    - Nordic
    - Nordic-bluish-accent
    - Nordic-darker
    - Nordic-Polar
  loop_control:
    loop_var: outer_item
