---
- name: Download `{{ outer_item }}` theme package
  get_url:
    url: "https://github.com/EliverLara/Nordic/releases/download/v2.1.0/{{ outer_item }}.tar.xz"
    dest: "/tmp/{{ outer_item }}.tar.xz"

- name: Ensures `/usr/share/themes/` folder exists
  file:
    path: /usr/share/themes/
    state: directory

- name: Unarchive `{{ outer_item }}` theme
  become: yes
  unarchive:
    src: /tmp/{{ outer_item }}.tar.xz
    dest: /usr/share/themes/
    remote_src: yes

- name: Clean `/tmp` archive
  file:
    state: absent
    path: /tmp/{{ outer_item }}.tar.xz
