---
- name: Install the required packages
  become: yes
  package: 
    name: "{{ item }}"
    state: latest
  with_items:
    - cups
    - lsb
    - system-config-printer

- name: Install EPSON driver from internet
  become: yes
  apt:
    deb: "https://download3.ebz.epson.net/dsc/f/03/00/13/43/81/ba6851ef53476ebdf3ee36600067ce4a3c81c032/epson-inkjet-printer-escpr_{{ printers.epson.driver_version }}-1lsb3.2_amd64.deb"
  when: printers.epson.enabled | default(False)
