---
- include_tasks: nfs.archlinux.yml
  when: ansible_os_family == "Archlinux"

- include_tasks: nfs.debian.yml
  when: ansible_os_family == "Debian"



- name: Configure NFS shares
  include_tasks: nfs-share.yml
  loop: "{{ nfs }}"
  loop_control:
    loop_var: outer_item
