---
- name: Deploying the service file for {{ item.name }} mount
  become: True
  template:
    src: service.mount.j2
    dest: /etc/systemd/system/mnt-{{ item.name }}.mount

- name: Ensure folder exists
  become: True
  file:
    path: "{{ item.where }}"
    state: directory

- name: Ensure the service is enable at boot
  become: True
  service:
    name: "mnt-{{ item.name }}.mount"
    enabled: yes
