---
- name: Deploying the service file for {{ outer_item.name }} mount
  become: yes
  template:
    src: service.mount.j2
    dest: /etc/systemd/system/mnt-{{ outer_item.name }}.mount

- name: Ensure folder exists
  become: yes
  file:
    path: "{{ outer_item.where }}"
    state: directory

- name: Ensure the service is enable at boot
  become: yes
  service:
    name: "mnt-{{ outer_item.name }}.mount"
    enabled: "{{ outer_item.is_enabled_at_boot | default(False) }}"
