---
- include_tasks: jenv.archlinux.yml
  when: ansible_os_family == "Archlinux"

- include_tasks: jenv.debian.yml
  when: ansible_os_family == "Debian"


# - name: Configure `jenv`
#   shell: ~/.jenv/bin/jenv add /usr/lib/jvm/java-{{ item }}-openjdk/
#   with_items: "{{ java.versions }}"
