---
- name: Install `konsole` package
  become: yes
  package: 
    name: konsole
    state: latest


- name: Ensures `~/.local/share/konsole` folder exists
  file:
    path: "~/.local/share/konsole/"
    state: directory

- name: Copy the `nord.colorscheme` file
  copy:
    src: nord.colorscheme
    dest: "~/.local/share/konsole/"

- name: Deploying `zsh.profile` file
  template:
    src: zsh.profile.j2
    dest: "~/.local/share/konsole/zsh.profile"


- name: Copy the `konsolerc` file
  copy:
    src: konsolerc
    dest: "~/.config/konsolerc"
