---
- name: Install `pulseaudio` configuration
  include_role:
    name: audio/pulseaudio
    apply: 
      tags: [pulseaudio]
  tags: [audio]

- name: Install `pasystray` package
  become: yes
  package:
    name: pasystray
    state: latest
  tags: [audio, pasystray]