---
- name: Install `arandr`
  include_role:
    name: screenlayout/arandr
    apply: 
      tags: [arandr]
  tags: [screenlayout]

- name: Install `autorandr`
  include_role:
    name: screenlayout/autorandr
    apply: 
      tags: [autorandr]
  tags: [screenlayout]