---
# - name: Install `arandr`
#   include_role:
#     name: screenlayout/arandr
#     apply: 
#       tags: [screenlayout, arandr]

- name: Install `autorandr`
  include_role:
    name: screenlayout/autorandr
    apply: 
      tags: [screenlayout, autorandr]