---
- name: Install `arandr` packages
  become: yes
  package: 
    name: "arandr"
    state: latest

- name: Install `autorandr`
  include_role:
    name: screenlayout/roles/autorandr
    apply: 
      tags: [autorandr]
  tags: [screenlayout]