---
- name: Add `regolith-linux` repository from PPA
  become: yes
  apt_repository:
    repo: ppa:regolith-linux/release


- name: Install `i3-gaps` package
  become: yes
  package: 
    name: i3-gaps
    state: latest


- name: Ensures `~/.config/i3` folder exists
  file:
    path: "~/.config/i3"
    state: directory

- name: Deploying the `i3` configuration file
  template:
    src: i3config.j2
    dest: "~/.config/i3/config"