---
- name: Install `discord` package from the internet
  become: yes
  apt:
    deb: https://dl.discordapp.net/apps/linux/{{ discord.version }}/discord-{{ discord.version }}.deb

# - name: First discord launch (used for the module installations)
#   shell: "(cmdpid=$BASHPID; (sleep 20; kill $cmdpid) & exec discord)"


- name: Install `betterdiscordctl`
  become: yes
  get_url:
    url: "https://raw.githubusercontent.com/bb010g/betterdiscordctl/master/betterdiscordctl"
    dest: /usr/local/bin
    mode: '0775'

- name: Install `betterdiscord` with `betterdiscordctl`
  shell: betterdiscordctl install
  ignore_errors: yes


- name: Ensures betterdiscord configuration folders exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "~/.config/BetterDiscord/themes"
  - "~/.config/BetterDiscord/data/stable"

- name: Copy the betterdiscord configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - {
    "src": "nordic.theme.css",
    "dest": "~/.config/BetterDiscord/themes/"
  }
  - {
    "src": "themes.json",
    "dest": "~/.config/BetterDiscord/data/stable/"
  }