---
- name: Install `feh` package
  become: yes
  package: 
    name: feh
    state: latest


- name: Ensures `~/.config/feh` folder exists
  file:
    path: "~/.config/feh"
    state: directory

- name: Check wallpapers
  fail:
    msg: "Warning: no wallpapers have been selected."
  when: wallpapers is undefined or wallpapers|length == 0
  ignore_errors: True

- name: Deploying the `launch.sh` file
  template:
    src: launch.sh.j2
    dest: "~/.config/feh/launch.sh"
    mode: '0754'