---
- name: Install `flameshot` package
  become: yes
  package: 
    name: flameshot
    state: latest


- name: Deploying the `flameshot` configuration file
  template:
    src: flameshot.ini.j2
    dest: "~/.config/flameshot/flameshot.ini"


- name: Ensures `{{ flameshot.savePath }}` folder exists
  file:
    path: "{{ flameshot.savePath }}"
    state: directory