---
- name: Copy `~/.aliases` file
  template:
    src: .aliases.j2
    dest: "~/.aliases"

- name: Download external aliases file
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.destination }}"
  with_items:
    - {
        "url": "https://raw.githubusercontent.com/ahmetb/kubectl-aliases/master/.kubectl_aliases",
        "destination": "~/.kubectl_aliases"
      }
    - {
        "url": "https://raw.githubusercontent.com/GitAlias/gitalias/main/gitalias.txt",
        "destination": "~/.git_aliases"
      }
    - {
        "url": "https://raw.githubusercontent.com/zer0beat/terraform-aliases/master/.terraform_aliases",
        "destination": "~/.terraform_aliases"
      }
