---
- name: Ensures folders exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "~/Documents/workspace-pro"
    - "~/Documents/workspace-perso"


- name: Copy `~/.gitconfig` file
  copy:
    src: .gitconfig
    dest: "~"

- name: Deploying `.gitconfig` file into workspaces
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {
      "src": "gitconfig-wper.j2",
      "dest": "~/.gitconfig-perso"
    }
    - {
      "src": "gitconfig-wpro.j2",
      "dest": "~/.gitconfig-pro"
    }
