---
- name: Ensures `~/.config/gtk-3.0` folder exists
  file:
    path: "~/.config/gtk-3.0"
    state: directory

- name: Deploying the `gtk-3.0` settings file
  template:
    src: gtk3settings.ini.j2
    dest: "~/.config/gtk-3.0/settings.ini"
