---
- name: Install `autorandr` packages
  become: yes
  pip: 
    name: "autorandr"


- name: Copy the `autorandr` configurations file
  copy:
    src: configurations
    dest: "~/.config"
    force: yes

- name: Copy the `autorandr` hook scripts file
  copy:
    src: hook_scripts
    dest: "~/.config"
    mode: '755'
    force: yes