---

- include_tasks: jdk/main.yml
  loop: "{{ java.versions }}"
  loop_control:
    loop_var: outer_item

- include_tasks: maven/main.yml
  tags: [java, maven]

- include_tasks: jenv/main.yml
  tags: [java, jenv]
