---
- include_tasks: git-secrets.archlinux.yml
  when: ansible_os_family == "Archlinux"

- include_tasks: git-secrets.debian.yml
  when: ansible_os_family == "Debian"


- name: Configure the default provider
  shell:
    cmd: git secrets --register-aws --global
