---
- name: Download `k3sup` installation script
  get_url:
    url: "https://get.k3sup.dev"
    dest: /tmp/get_k3sup.sh
    mode: '0700'

- name: Execute the `k3sup` setup file
  shell: /tmp/get_k3sup.sh

- name: Move the executable file
  become: yes
  copy:
    src: k3sup
    dest: /usr/local/bin/k3sup
    remote_src: yes
    mode: '0755'

- name: Clean the executable file
  file:
    state: absent
    path: k3sup

- name: Clean `/tmp` folder
  file:
    state: absent
    path: /tmp/get_k3sup.sh
