---
- name: Install `code` dependencies
  become: yes
  package:
    name: xclip
    state: latest

- name: Install `code` software
  kewlfft.aur.aur:
    use: yay
    name: visual-studio-code-bin
    state: present

- name: Install `codium` software
  kewlfft.aur.aur:
    use: yay
    name: vscodium-bin
    state: present
