---
- include_tasks: alacritty.archlinux.yml
  when: ansible_os_family == "Archlinux"

- include_tasks: alacritty.debian.yml
  when: ansible_os_family == "Debian"



- name: Ensures `~/.config/alacritty` folder exists
  file:
    path: "~/.config/alacritty/"
    state: directory

- name: Copy the nord theme file
  copy:
    src: nord.yml
    dest: "~/.config/alacritty/"

- name: Deploying configuration file
  template:
    src: alacritty.yml.j2
    dest: "~/.config/alacritty/alacritty.yml"
