---
- name: Download `balenaEtcher` archive from the internet
  get_url:
    url: "https://github.com/balena-io/etcher/releases/download/v{{ balenaEtcher.version }}/balena-etcher-electron-{{ balenaEtcher.version }}-linux-x64.zip"
    dest: /tmp/balenaEtcher.zip
    mode: '0755'

- name: Ensures `/tmp/balenaEtcher` temporary folder exists
  file:
    path: /tmp/balenaEtcher/
    state: directory

- name: Extract `balenaEtcher` files
  unarchive:
    src: /tmp/balenaEtcher.zip
    dest: /tmp/balenaEtcher
    remote_src: yes

- name: Move the executable file
  become: yes
  copy:
    src: /tmp/balenaEtcher/balenaEtcher-{{ balenaEtcher.version }}-x64.AppImage
    dest: /usr/local/bin/balenaEtcher.AppImage
    remote_src: yes
    mode: '0755'

- name: Clean `/tmp` folder
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /tmp/balenaEtcher.zip
    - /tmp/balenaEtcher


- name: Creates balenaEtcher folder
  become: yes
  file:
    path: "/usr/share/balenaEtcher/"
    state: directory

- name: Copy icon file
  become: yes
  copy:
    src: "balenaEtcher.png"
    dest: /usr/share/balenaEtcher/balenaEtcher.png


- name: Copy desktop file
  become: yes
  copy:
    src: "balenaEtcher.desktop"
    dest: /usr/share/applications/balenaEtcher.desktop
