---

- name: Install `ckb-next` software
  include_role:
    name: peripherals/ckb-next
    apply: 
      tags: [corsair]
  tags: [peripherals]
  when: have_you_a_some_corsair_peripherals | default(False)
