---
- name: Download `ngrok` archive from the internet
  get_url:
    url: "{{ ngrok_download_link }}"
    dest: /tmp/{{ ngrok_download_link.split('/')[-1] }}
    mode: '0755'

- name: Extract `ngrok` files
  become: yes
  unarchive:
    src: /tmp/{{ ngrok_download_link.split('/')[-1] }}
    dest: /usr/local/bin
    remote_src: yes


- name: Ensures `~/.ngrok` folder exists
  file:
    path: ~/.ngrok
    state: directory

- name: Deploying the `ngrok` configuration file
  template:
    src: ngrok.yml.j2
    dest: "~/.ngrok/ngrok.yml"


- name: Clean `/tmp` folder
  file:
    state: absent
    path: /tmp/{{ ngrok_download_link.split('/')[-1] }}