---
- name: Install `touchegg` and `touché`
  kewlfft.aur.aur:
    use: yay
    name: 
    - touchegg
    - touche
    state: latest

- name: Copy `touchegg` configuration files
  become: yes
  copy:
    src: "{{ item }}"
    dest: ~/.config/touchegg/
  with_items:
    - touche.sh
    - touchegg.conf

- name: Ensure `touchegg` is enabled
  become: yes
  service:
    name: touchegg
    enabled: yes
    state: started
