---
- include_tasks: mailspring.archlinux.yml
  when: ansible_os_family == "Archlinux"

- include_tasks: mailspring.debian.yml
  when: ansible_os_family == "Debian"



- name: Ensures `~/.config/Mailspring/packages/` folder exists
  file:
    path: ~/.config/Mailspring/packages/
    state: directory

- name: Download `mailspring-nord-theme` repository
  git:
    repo: https://github.com/faraadi/mailspring-nord-theme
    dest: ~/.config/Mailspring/packages/mailspring-nord-theme
