---
- name: Install `rofi` package
  become: yes
  package: 
    name: rofi
    state: latest


- name: Ensures rofi configuration folder exists
  file:
    path: ~/.config/rofi
    state: directory

- name: Copy launcher script
  copy:
    src: launch.sh
    dest: ~/.config/rofi

- name: Change `launch.sh` file permissions
  file:
    path: ~/.config/rofi/launch.sh
    mode: '0754'

- name: Deploying the rofi theme file
  template:
    src: nordic.rasi.j2
    dest:  ~/.config/rofi/config.rasi
