---
- include_tasks: cura.archlinux.yml
  when: ansible_os_family == "Archlinux"

- include_tasks: cura.debian.yml
  when: ansible_os_family == "Debian"



- name: Install the cura's profiles for the Wanhao France D12-230
  include_tasks: wanhao-france-d12-profiles.yml
  when: "'wanhao-france-d12' in cura.additionnal_profiles"
