---
- name: Install colorscheme
  include_role:
    name: appearance/roles/colorscheme
    apply: 
      tags: [appearance, colorscheme]
  tags: [appearance]

- name: Install themes
  include_role:
    name: appearance/roles/themes
    apply: 
      tags: [appearance, themes]
  tags: [appearance]

- name: Install icons
  include_role:
    name: appearance/roles/icons
    apply: 
      tags: [appearance, icons]
  tags: [appearance]

- name: Install cursors
  include_role:
    name: appearance/roles/cursors
    apply: 
      tags: [appearance, cursors]
  tags: [cursors]

- name: Install fonts
  include_role:
    name: appearance/roles/fonts
    apply: 
      tags: [appearance, fonts]
  tags: [appearance]


- name: Ensures `~/.config/gtk-3.0` folder exists
  file:
    path: "~/.config/gtk-3.0"
    state: directory

- name: Deploying the `gtk-3.0` settings file
  template:
    src: gtk3settings.ini.j2
    dest: "~/.config/gtk-3.0/settings.ini"