---
- include_tasks: tasks/get_latest_version_from_github.yml
  loop: 
  - kubernetes-sigs/kind
  loop_control:
    loop_var: outer_item

- name: Download `kind`
  become: yes
  get_url:
    url: https://kind.sigs.k8s.io/dl/{{ version }}/kind-Linux-amd64
    dest: /usr/local/bin/kind
    mode: '0755'
