---
- name: Download `caskaydia-cove` font archive
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ caskaydia_cove.version }}/CascadiaCode.zip"
    dest: /tmp/caskaydia-cove.zip

- name: Ensures `/tmp/caskaydia-cove` temporary folder exists
  file:
    path: /tmp/caskaydia-cove/
    state: directory

- name: Extract `caskaydia-cove` font files
  unarchive:
    src: /tmp/caskaydia-cove.zip
    dest: /tmp/caskaydia-cove/
    remote_src: yes

- name: Ensures `/usr/share/fonts/truetype/caskaydia-cove` folder exists
  become: yes
  file:
    path: /usr/share/fonts/truetype/caskaydia-cove/
    state: directory

- name: Prepare list of `*.ttf` files to move
  find:
    paths:
    - "/tmp/caskaydia-cove/"
    patterns: '.*([a-zA-Z]+).ttf'
    file_type: file
    use_regex: yes
  register: ttf_file_list

- name: Print return information from the previous task
  debug:
    msg: "{{ ttf_file_list.matched }} files matched."

- name: Move the `*.ttf` files
  become: yes
  copy:
    src: "{{ item.path }}"
    dest: "/usr/share/fonts/truetype/caskaydia-cove/"
    remote_src: yes
  with_items:
    - "{{ ttf_file_list.files }}"

- name: Clean `/tmp` folder
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /tmp/caskaydia-cove.zip
    - /tmp/caskaydia-cove
