---
#
# dev
#

- name: Install `jq` software
  become: yes
  package:
    name: jq
    state: latest
  tags: [cli, dev, jq]
  when: jq.enabled | default(False)

- include_tasks: ngrok/main.yml
  tags: [cli, dev, ngrok]
  when: ngrok.enabled | default(False)

- include_tasks: sonar-scanner/main.yml
  tags: [cli, dev, sonarScanner]
  when: sonarScanner.enabled | default(False)

- include_tasks: terraform/main.yml
  tags: [cli, dev, terraform]
  when: terraform.enabled | default(False)

- include_tasks: vault/main.yml
  tags: [cli, dev, vault]
  when: vault.enabled | default(False)


#
# utils
#

- include_tasks: asdf/main.yml
  tags: [cli, utils, asdf]
  when: asdf.enabled | default(False)

- include_tasks: bat/main.yml
  tags: [cli, utils, bat]
  when: bat.enabled | default(False)

- name: Install `bpytop` software
  become: yes
  package:
    name: bpytop
    state: latest
  tags: [cli, utils, bpytop]
  when: bpytop.enabled | default(False)

- name: Install `dig` software
  become: yes
  package:
    name: bind
    state: latest
  tags: [cli, dev, dig]
  when: dig.enabled | default(False) and ansible_os_family == "Archlinux"

- include_tasks: exa/main.yml
  tags: [cli, utils, exa]
  when: exa.enabled | default(False)

- include_tasks: fd/main.yml
  tags: [cli, utils, fd]
  when: fd.enabled | default(False)

- include_tasks: fzf/main.yml
  tags: [cli, utils, fzf]
  when: fzf.enabled | default(False)

- include_tasks: gfold/main.yml
  tags: [cli, utils, gfold]
  when: gfold.enabled | default(False)

- name: Install `gparted` software
  become: yes
  package:
    name: gparted
    state: latest
  tags: [cli, utils, gparted]
  when: gparted.enabled | default(False)

- name: Install `htop` software
  become: yes
  package:
    name: htop
    state: latest
  tags: [cli, utils, htop]
  when: htop.enabled | default(False)

- name: Install `nala` software
  become: yes
  package:
    name: nala
    state: latest
  tags: [cli, utils, nala]
  when: (nala.enabled | default(False)) & ansible_os_family == "Debian"

- include_tasks: nano/main.yml
  tags: [cli, utils, nano]
  when: nano.enabled | default(False)

- include_tasks: procs/main.yml
  tags: [cli, utils, procs]
  when: procs.enabled | default(False)

- name: Install `ripgrep` software
  become: yes
  package:
    name: ripgrep
    state: latest
  tags: [cli, utils, ripgrep]
  when: ripgrep.enabled | default(False)

- include_tasks: zoxide/main.yml
  tags: [cli, utils, zoxide]
  when: zoxide.enabled | default(False)


#
# misc
#

- name: Install `imagemagick` software
  become: yes
  package:
    name: imagemagick
    state: latest
  tags: [cli, utils, imagemagick]
  when: imagemagick.enabled | default(False)
