---
- name: Install `exa` cli
  include_role:
    name: cli/exa
    apply: 
      tags: [exa]
  tags: [cli]

- name: Install `kubectl` cli
  include_role:
    name: cli/kubectl
    apply: 
      tags: [kubectl]
  tags: [cli]
  when: kubectl.enabled | default(False)

- name: Install `kubectx` cli
  include_role:
    name: cli/kubectx
    apply: 
      tags: [kubectl, kubectx]
  tags: [cli]
  when: kubectl.enabled | default(False)

- name: Install `nano` cli
  include_role:
    name: cli/nano
    apply: 
      tags: [nano]
  tags: [cli]

- name: Install `ngrok` cli
  include_role:
    name: cli/ngrok
    apply: 
      tags: [ngrok]
  tags: [cli]
  when: ngrok.enabled | default(False)
