---


#
# dev
#

- name: Install "dev" cli softwares (with `{{ ansible_pkg_mgr }}` package manager)
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - helm
    - kompose
    - kubectl
    - kubectx
    - terraform
    - vault
  tags: [cli]

- name: Install "dev" cli softwares (with `yay` package manager)
  kewlfft.aur.aur:
    use: yay
    name: "{{ item }}"
    state: present
  with_items:
    - ngrok
  tags: [cli]


#
# misc
#

- name: Install "misc" cli softwares
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - bat
    - fzf
    - exa
    - nano
    - ripgrep
    - procs
    - zoxide
    - fd
    - gfold
  tags: [cli]
